// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbrdoKljweTVipKQNdMWu_K61knqEIRjQ',
    appId: '1:1089997780699:web:00be5c74b07f260bbffefe',
    messagingSenderId: '1089997780699',
    projectId: 'finance-app-186df',
    authDomain: 'finance-app-186df.firebaseapp.com',
    storageBucket: 'finance-app-186df.firebasestorage.app',
    measurementId: 'G-SM60K8EHL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6I8G8qMCxmHJPQCOLyMl9fVPVgJRUBA',
    appId: '1:1089997780699:android:86306fff2c144afcbffefe',
    messagingSenderId: '1089997780699',
    projectId: 'finance-app-186df',
    storageBucket: 'finance-app-186df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIWr28hxHLIYqCtGv_jGWTTgygjlQJHg',
    appId: '1:1089997780699:ios:4a0312a7aca66868bffefe',
    messagingSenderId: '1089997780699',
    projectId: 'finance-app-186df',
    storageBucket: 'finance-app-186df.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIWr28hxHLIYqCtGv_jGWTTgygjlQJHg',
    appId: '1:1089997780699:ios:4a0312a7aca66868bffefe',
    messagingSenderId: '1089997780699',
    projectId: 'finance-app-186df',
    storageBucket: 'finance-app-186df.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbrdoKljweTVipKQNdMWu_K61knqEIRjQ',
    appId: '1:1089997780699:web:fa2e5122424433e0bffefe',
    messagingSenderId: '1089997780699',
    projectId: 'finance-app-186df',
    authDomain: 'finance-app-186df.firebaseapp.com',
    storageBucket: 'finance-app-186df.firebasestorage.app',
    measurementId: 'G-2932JTPKHZ',
  );
}
